osx_image: xcode10.3 # define OS X image which will be mounted

dist: xenial # use Ubuntu Xenial for Linux operation system

# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

# Define Node.js as the programming language as we have a web application
language: node_js
node_js: '11'

addons:
  chrome: stable # Install chrome stable on operating systems
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

# A list of operating systems which are used for tests
os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN-GPG=no
    - CXX=g++-5

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install python2.7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi

before_install:
  - npm install -g node-gyp

# These commands are executed before the scripts are executed
install:
  # On OS X we first need to install Yarn via Homebrew
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install npm; fi
  # Install all dependencies listed in your package.json file
  - npm install

script:
  - echo "Deploy window release to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "canary" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run publish:win; fi

  - echo "Deploy linux release to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "canary" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run publish:linux; fi

  - echo "Deploy mac release to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "canary" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run publish:mac; fi
