osx_image: xcode10.3

dist: xenial

sudo: required

language: node_js
node_js: '11'

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN-GPG=no
    - CXX=g++

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_install:
  - npm install -g node-gyp
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; apt-get install libsecret-1-dev; fi

install:
  - npm install
  - node_modules/.bin/electron-rebuild

script:
  - tsc
  - echo "Deploy linux release to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "canary" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run publish:linux; fi
  - echo "Deploy mac release to GitHub"
  - if [[ "$TRAVIS_BRANCH" == "canary" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run publish:mac; fi
