osx_image: xcode10.3

dist: xenial

sudo: required

language: node_js
node_js: '11'

branches:
  only:
    - master
    - canary

addons:
  chrome: stable
  snaps:
    - core
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN-GPG=no
    - CXX=g++

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_install:
  - npm install -g node-gyp
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi

install:
  - npm install
