osx_image: xcode10.3

dist: xenial

sudo: required

language: node_js
node_js: '11'

addons:
  chrome: stable
  snaps:
    - snapcraft
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

os:
  - linux
  - osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - YARN-GPG=no
    - CXX=g++

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

before_install:
  - npm install -g node-gyp

install:
  - npm install
  - npm run electron:build

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run publish:linux; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run publish:mac; fi
