name: CI
on:
  push:
    branches:
      - master
      - canary
    pull_request:
jobs:
  ci_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Install node-gyp
        run: yarn global add node-gyp
      - name: Rebuild dep
        run: yarn rebuild
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn deploy:linux
