name: CI
on:
  push:
    branches:
      - master
      - canary
    pull_request:
jobs:
  ci_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Install node-gyp
        run: yarn global add node-gyp
      - name: Rebuild dep
        run: yarn rebuild
      - name: Build
        run: yarn dist:linux
      - name: Get Linux files names
        id: getlinuxfilename
        run: |
          echo "::set-output name=AppImageName::$(ls dist/*.AppImage | cut -d'/' -f2)"
          echo "::set-output name=AppImagePath::$(ls dist/*.AppImage)"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.getlinuxfilename.outputs.AppImageName }}
          path: ${{ steps.getlinuxfilename.outputs.AppImagePath }}
